name: CI CD deploy atlan

on:
  push:
    branches:
      - main

jobs:

  # ----------------------------------------
  # BUILD & PUSH DOCKER IMAGE
  # ----------------------------------------

  build-and-push:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/atlan-demo:latest .

      - name: Push Docker image
        run: |
          docker push \
            ${{ secrets.DOCKER_USERNAME }}/atlan-demo:latest


  # ----------------------------------------
  # COPY COMPOSE FILE TO SERVER
  # ----------------------------------------

  copy-compose-file:

    runs-on: ubuntu-latest
    needs: build-and-push

    steps:

      # ⭐ ADD THIS LINE
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy docker-compose.yml to server
        uses: appleboy/scp-action@v0.1.7

        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "docker-compose.yml"
          target: "/home/ubuntu/"


  # ----------------------------------------
  # DEPLOY TO SERVER
  # ----------------------------------------

  deploy:

    runs-on: ubuntu-latest
    needs: copy-compose-file

    steps:

      - name: Deploy to Atlan Server
        uses: appleboy/ssh-action@v1.0.0

        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}

          script: |

            echo "========== START DEPLOY =========="

            echo "Pulling latest Docker image..."

            sudo docker pull \
              ${{ secrets.DOCKER_USERNAME }}/atlan-demo:latest

            echo "Stopping existing services..."

            sudo docker compose down || true

            echo "Pulling latest service images..."

            sudo docker compose pull

            echo "Starting services..."

            sudo docker compose up -d

            echo "Cleaning unused images..."

            sudo docker image prune -f

            echo "========== DEPLOY COMPLETE =========="